import Head from "next/head";
import Link from "next/link";

const { BLOG_URL, CONTENT_API_KEY } = process.env;

async function getPosts() {
  const res = await fetch(
    `${BLOG_URL}/ghost/api/v3/content/posts/?key=${CONTENT_API_KEY}&fields=title,slug,custom_excerpt`
  ).then((res) => res.json());

  const posts = res.posts;

  return posts;
}

async function getTagss() {
  const res = await fetch(
    `${BLOG_URL}/ghost/api/v3/content/tags/?key=${CONTENT_API_KEY}&fields=name,slug`
  ).then((res) => res.json());

  const tags = res.tags;

  return tags;
}

async function getfeatures() {
  const res = await fetch(
    `${BLOG_URL}/ghost/api/v3/content/posts/?key=${CONTENT_API_KEY}&filter=featured:true`
  ).then((res) => res.json());

  const features = res.posts;

  return features;
}

export const getStaticProps = async ({ params }) => {
  const posts = await getPosts();
  const tags = await getTagss();
  const features = await getfeatures();
  return {
    revalidate: 10,
    props: { posts, tags, features }
  };
};

export default function Home({ posts, tags, features }) {
  return (
    <div>
      <Head>
        <title>Update News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Recent News</h2>
        <ul>
          {posts.map((post, index) => {
            return (
              <li key={post.slug}>
                <Link href={`/news/${encodeURIComponent(post.slug)}`}>
                  <a>{post.title}</a>
                </Link>
              </li>
            );
          })}
        </ul>
        <h2>Tags list</h2>
        <ul>
          {tags.map((tag, index) => {
            return (
              <li key={tag.slug}>
                <Link
                  href={`/tags/${tag.name}/${encodeURIComponent(tag.slug)}`}
                >
                  <a>{tag.name}</a>
                </Link>
              </li>
            );
          })}
        </ul>
        <h2>Feauture news list</h2>
        <ul>
          {features.map((feature, index) => {
            return <li key={feature.slug}>{feature.title}</li>;
          })}
        </ul>
      </main>
    </div>
  );
}
